version: '3.1'

services:
  springboot:
    image: 111992/spring-boot-mongo:latest
    restart: always
    container_name: springboot
    ports:
      - 9090:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
  mongo:
    image: mongo
    container_name: springboot-mongo
    volumes:
      - data:/data/db
      - data-bkp:/data/bkp
    restart: always
volumes:
  data:
    external: true
  data-bkp:
    external: true
networks:
  default:
    external:
      name:  flipkartnetwork
