version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  django:
    image: django
    restart: always
    ports:
      - 8001:8000    
volumes:
  data:
    external: true
  data-bkp:
    external: true
networks:
  default:
    external:
      name:  flipkartnetwork
