version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: PostgresContainer
    ports:
      - 8080:8080
 
volumes:
  data:
    external: true
  data-bkp:
    external: true